import { TripSchema, emptyState, type Trip } from './schema.js';
export function exampleTrip(): Trip {
  return TripSchema.parse({
    schemaVersion: '1',
    id: 'example-trip',
    revision: 1,
    updatedAt: new Date().toISOString(),
    state: emptyState(),
    plan: {
      title: 'Un giorno a Borgo Blu',
      subtitle: 'Un piccolo viaggio di esempio',
      destinations: ['Borgo Blu'],
      startDate: '2026-11-12',
      endDate: '2026-11-12',
      timezone: 'Europe/Rome',
      dateStatus: 'confirmed',
      travellers: [
        { id: 'traveller-one', name: 'Io' },
        { id: 'traveller-two', name: 'Compagno di viaggio' },
      ],
      days: [
        {
          id: 'day-one',
          date: '2026-11-12',
          title: 'Tra piazze e giardini',
          summary: 'Luoghi inventati per provare Passo.',
          stepIds: ['square', 'walk', 'museum'],
        },
      ],
      steps: [
        {
          id: 'square',
          kind: 'stop',
          title: 'La piazza del borgo',
          category: 'visit',
          placeId: 'blue-square',
          start: '2026-11-12T09:00:00+01:00',
          end: '2026-11-12T10:00:00+01:00',
          summary: 'Un caffè e il primo sguardo alla città.',
        },
        {
          id: 'walk',
          kind: 'leg',
          title: 'Verso il museo',
          fromPlaceId: 'blue-square',
          toPlaceId: 'blue-museum',
          mode: 'walk',
          durationMinutes: 15,
          start: '2026-11-12T10:00:00+01:00',
          end: '2026-11-12T10:15:00+01:00',
          streets: ['Via dei Giardini'],
          pois: [{ placeId: 'blue-garden', note: 'Una pausa tra gli alberi.', detourMinutes: 0 }],
          summary: 'Una passeggiata attraverso il giardino.',
        },
        {
          id: 'museum',
          kind: 'stop',
          title: 'Museo del borgo',
          category: 'visit',
          placeId: 'blue-museum',
          start: '2026-11-12T10:15:00+01:00',
          end: '2026-11-12T11:45:00+01:00',
          summary: 'Storie, arte e curiosità del borgo.',
        },
      ],
      places: [
        {
          id: 'blue-square',
          name: 'Piazza Blu',
          address: 'Borgo Blu',
          description: 'Questo luogo è inventato.',
          details: 'Una piazza per esplorare le funzionalità del viaggio.',
        },
        {
          id: 'blue-museum',
          name: 'Museo del borgo',
          address: 'Via dei Giardini 12, Borgo Blu',
          description: 'Un museo immaginario.',
          details: 'La visita dura circa un’ora e mezza.',
          openingHours: 'Esempio: 09:00–18:00',
          bookingUrl: 'https://example.com/tickets',
        },
        {
          id: 'blue-garden',
          name: 'Giardino segreto',
          address: 'Via dei Giardini, Borgo Blu',
          description: 'Un giardino immaginario lungo il percorso.',
        },
      ],
      sources: [],
      costs: [
        {
          id: 'museum-admission',
          title: 'Museo del borgo',
          category: 'admission',
          min: 15,
          max: 15,
          currency: 'EUR',
          basis: 'person',
          inclusion: 'base',
          status: 'estimate',
          stepIds: ['museum'],
        },
      ],
      tasks: [
        {
          id: 'book-museum',
          title: 'Prenotare il museo',
          description: 'Un’attività di esempio.',
          priority: 'high',
          stepId: 'museum',
          url: 'https://example.com/tickets',
        },
      ],
    },
  });
}
